FROM nvidia/cuda:12.4.0-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y python3.12 python3-pip
WORKDIR /app
COPY pyproject.toml ./
RUN pip install uv && uv pip install --system .
COPY src ./src
COPY ml ./ml
